### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by gabrielteotonio** [rdblue/jupyter-zeppelin#4]
`Traceback (most recent call last):
  File "jupyter-zeppelin.py", line 181, in <module>
    name, content = convert_json(read_io(zeppelin_note_path))
  File "jupyter-zeppelin.py", line 62, in convert_json
    return convert_parsed(json.load(zeppelin_json))
  File "/usr/lib64/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
`

**Comment by gabrielteotonio** [comment]
If pass an output path as `out-note.ipynb` there will not be error but the output file wasn't created.
